version: '3.1'

services:
  core:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    links:
      - db
      - redis
    networks:
      - outside
      - internal

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_DB: magellan
    volumes:
      - ./containers_data/postgres:/var/lib/postgresql/data
    networks:
      - internal

  broker:
    image: rabbitmq:3.7-alpine
    restart: always
    networks:
      - internal

networks:
  outside:
  internal:
    internal: true
