version: '3.1'

services:
  core:
    build: .
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    links:
      - db
      - broker
    networks:
      - outside
      - internal

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_DB: magellan
    volumes:
      - ./containers_data/postgres:/var/lib/postgresql/data
    networks:
      - internal

  broker:
    image: rabbitmq:3.7-alpine
    # image: rabbitmq:3.7-management-alpine # Uncomment this if you want to access to RabbitMQ management interface (for debuging)
    restart: always
    ports:
      # - 8082:15672 # Uncomment this if you want to access to RabbitMQ management interface (for debuging)
      - 5672:5672
    networks:
      - outside
      - internal

networks:
  outside:
  internal:
    internal: true
