# Generated by Django 2.0.4 on 2018-05-08 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workgroup', models.CharField(default='WORKGROUP', max_length=14, unique=True)),
                ('caseSensitive', models.BooleanField(default=0)),
                ('homes', models.BooleanField(default=1)),
                ('minProtocol', models.CharField(choices=[('NT1', 'Current up to date version of the protocol. Used by Windows NT. Known as CIFS'), ('SMB2', 'Re-implementation of the SMB protocol. Used by Windows Vista and later versions of Windows. SMB2 has sub protocols available'), ('SMB2_02', 'The earliest SMB2 version'), ('SMB2_10', 'Windows 7 SMB2 version'), ('SMB2_22', 'Early Windows 8 SMB2 version'), ('SMB2_24', 'Windows 8 beta SMB2 version'), ('SMB3', 'New label of the SMB2 protocol rewrited'), ('SMB3_00', 'Windows 8 SMB3 version. (mostly the same as SMB2_24)'), ('SMB3_02', 'Windows 8.1 SMB3 version'), ('SMB3_10', 'Early Windows 10 technical preview SMB3 version'), ('SMB3_11', 'Windows 10 technical preview SMB3 version'), ('LANMAN1', 'First modern version of the protocol. Long filename support'), ('LANMAN2', 'Updates to Lanman1 protocol')], default='SMB2', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=None, unique=True)),
                ('description', models.TextField()),
                ('path', models.TextField(null=None, unique=True)),
                ('ownerType', models.BooleanField(default=0, null=None)),
                ('ownerId', models.UUIDField()),
                ('allowGuest', models.BooleanField(default=0)),
                ('readOnly', models.BooleanField(default=0)),
                ('browseable', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
