# Generated by Django 2.0.4 on 2018-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(unique=True, verbose_name='Hostname or IP of the client')),
                ('ignore', models.BooleanField(default=0)),
                ('kod', models.BooleanField(default=0)),
                ('limited', models.BooleanField(default=0)),
                ('lowpriotrap', models.BooleanField(default=0)),
                ('nomodify', models.BooleanField(default=0)),
                ('noquery', models.BooleanField(default=0)),
                ('nopeer', models.BooleanField(default=0)),
                ('noserve', models.BooleanField(default=0)),
                ('notrap', models.BooleanField(default=0)),
                ('ntpport', models.BooleanField(default=0)),
                ('version', models.BooleanField(default=0)),
                ('enabled', models.BooleanField(default=1, verbose_name='Enable rule')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(unique=True, verbose_name='Hostname or IP of the NTP server')),
                ('enabled', models.BooleanField(default=1, verbose_name='Enable rule')),
            ],
        ),
    ]
